'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { RxHamburgerMenu } from 'react-icons/rx';
import { usePathname } from 'next/navigation';
import { Link } from 'react-scroll';
import Footer from './pageComponents/Footer';
import Image from 'next/image';
import { useState } from 'react';
import { animate, motion } from 'framer-motion';
import Navbar from './components/Navbar';
const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <main className="flex flex-col relative min-h-screen">
          {pathname !== '/Login' && <Navbar />}
          <div className="flex-grow flex-1 ">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
