'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { RxHamburgerMenu } from 'react-icons/rx';
import { usePathname } from 'next/navigation';
import { Link } from 'react-scroll';
import Footer from './pageComponents/Footer';
import logo from './assets/logoBlack.svg';
import Image from 'next/image';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const pathname = usePathname();
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        {pathname !== '/Login' && (
          <header className="flex w-full h-max justify-between items-center py-2 px-4  bg-slate-100 shadow-lg ">
            <div>
              <Image
                src={logo}
                alt="moouv"
                width={200}
                height={200}
                className="w-40 sm:w-48"
              />
            </div>

            <ul className="hidden md:flex gap-5 font-medium">
              <li>
                <Link
                  to="service"
                  className="cursor-pointer"
                  smooth={true}
                  duration={800}
                >
                  Service
                </Link>
              </li>
              <li className="cursor-pointer">
                <Link to="vision" smooth={true} duration={800}>
                  Vision
                </Link>
              </li>
              <li>
                {' '}
                <Link
                  to="faq"
                  className="cursor-pointer"
                  smooth={true}
                  duration={800}
                >
                  FAQ
                </Link>
              </li>
              <li>
                {' '}
                <Link
                  to="contact"
                  className="cursor-pointer"
                  smooth={true}
                  duration={800}
                >
                  Kontakt
                </Link>
              </li>
            </ul>
            <button
              className={`hidden md:block bg-primary text-md text-white rounded-md px-3 py-2`}
            >
              Anmelden
            </button>
            <RxHamburgerMenu size={25} className="md:hidden cursor-pointer" />
          </header>
        )}
        {children}
        <Footer />
      </body>
    </html>
  );
}
